version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
    rust: latest

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
